20.Б10-мм, Мищенко Станислав, 2.5
mi-sts/spbu_2020_c_homeworks pull request #10
Opened 2020-09-30 21:10 UTC by mi-sts

2020-10-01 19:50 UTC, SpirinEgor requested changes
Сразу для двух файлов: вынеси в отдельную функцию.
Также делать 2 файла не надо, просто из main вызови 2 разные функции и выведи их результат

2020-10-01 19:50 UTC, SpirinEgor commented on CMakeLists.txt
> -add_executable(task_2.1 homework_2/task_1.c)
И тут что-то лишнее удаляется.

2020-10-05 13:20 UTC, nbirillo requested changes

2020-10-05 13:20 UTC, nbirillo commented on homework_2/task_5.c
> +    }
А почему для рекурсии у тебя отдельная функция, а для интеративной версии нет? вынеси вычисление факториала в отдельную функцию

2020-10-05 13:20 UTC, nbirillo commented on homework_2/task_5.c
> +}
Ты эту функцию используешь не только тут кажется, отличается только сообщение. Может быть ты вынесешь ее в отдельный файлик и будешь передавать параметром  (например тут `"Введите число, факториал которого хотите найти: "`)?

2020-10-09 11:51 UTC, nbirillo requested changes

2020-10-09 11:51 UTC, nbirillo commented on homework_2/task_5.c
> +int main()
![image](https://user-images.githubusercontent.com/8993915/95579739-d738b500-0a3e-11eb-8144-e8c4820c1bd6.png)

2020-10-09 11:51 UTC, nbirillo commented on homework_2/task_5.c
> +    printIterativeFactorial(number);
А еще у тебя все эти функции принимают int, а ты шлешь long long

2020-10-09 11:51 UTC, nbirillo commented
И конфликты почини)

2020-10-09 14:29 UTC, mi-sts commented on homework_2/task_5.c
> +int main()
Я изменил все переменные на long long в новом коммите, но даже в этой версии программы у меня почему-то такой ошибки не возникало(на скрине как раз эта версия без long long)
![изображение](https://user-images.githubusercontent.com/66365072/95595321-b3806980-0a54-11eb-9995-d833df5ed2ce.png)

2020-10-09 14:38 UTC, mi-sts commented on homework_2/task_5.c
> +int main()
Понял, у меня не возвращался number из функции nonnegativeNumberInut()

2020-10-12 06:52 UTC, nbirillo approved these changes
Поправь конфликты и зачтем)

2020-10-12 14:58 UTC, nbirillo approved these changes
Зачтено!

2020-10-12 14:58 UTC, merged