20.Б10-мм, Мищенко Станислав, 2.4
mi-sts/spbu_2020_c_homeworks pull request #11
Opened 2020-09-30 22:03 UTC by mi-sts

2020-10-01 19:48 UTC, SpirinEgor requested changes

2020-10-01 19:48 UTC, SpirinEgor commented on CMakeLists.txt
> -add_executable(task_2.1 homework_2/task_1.c)
Опять что-то зря удаляется

2020-10-01 19:48 UTC, SpirinEgor commented on homework_2/task_4.c
> +int main()
Подели на функции

2020-10-01 19:48 UTC, SpirinEgor commented on homework_2/task_4.c
> +    printf("Получившееся перестановкой цифр минимальное натуральное число: %d", resultNumber);
Так вроде ведущие нули могут вылезти. Надо бы их за первую цифру спрятать

2020-10-01 23:07 UTC, mi-sts commented on homework_2/task_4.c
> +    printf("Получившееся перестановкой цифр минимальное натуральное число: %d", resultNumber);
Так я же чуть в выше в коде сделал специальнно для этого инициализацию страшего ненулевого разряда, после чего запомнил его индекс, чтобы не наткнуться на него при поиске остальных разрядов

2020-10-05 13:17 UTC, nbirillo requested changes

2020-10-05 13:17 UTC, nbirillo commented on homework_2/task_4.c
> +int main()
Оно натуральное :) 
![image](https://user-images.githubusercontent.com/8993915/95083877-c7129400-0725-11eb-911c-c90e76891fbe.png)
Сделай, чтобы с большими тоже работало

2020-10-05 13:17 UTC, nbirillo commented on homework_2/task_4.c
> +        }
Сложно и не очень эффективно. Еще все время `getNumberDigit` вызывается. Может быть получится придумать, как это упростить?

2020-10-05 13:17 UTC, nbirillo commented on homework_2/task_4.c
> +int findMinimumNaturalNumber(int number)
А еще опять большая функция, которую можно поделить на маленькие

2020-10-09 11:56 UTC, nbirillo requested changes

2020-10-09 11:56 UTC, nbirillo commented on homework_2/task_4.c
> +int main()
Кажется, что так не должно быть)
![image](https://user-images.githubusercontent.com/8993915/95579953-2d0d5d00-0a3f-11eb-886a-0dcf54d07774.png)
А еще у тебя Valgrind ругается
![image](https://user-images.githubusercontent.com/8993915/95579993-3d253c80-0a3f-11eb-939c-99d3e09d1cb4.png)

2020-10-09 11:56 UTC, nbirillo commented on library/commonUtils/inputFunctions.c
> +long long naturalNumberInput(char* preInputMessage)
Она `long long`, но ничего не возвращает

2020-10-09 11:56 UTC, nbirillo commented on homework_2/task_4.c
> +    long long minimumNaturalNumber = findMinimumNaturalNumber(number);
Давай лучше `minimumNaturalNumber` заменим на `minNaturalNumber` (и в имени функции тоже)

2020-10-09 11:56 UTC, nbirillo commented
и конфликты еще)

2020-10-12 06:50 UTC, nbirillo approved these changes
Зачтено!

2020-10-12 06:50 UTC, merged