20.Б10-мм, Мищенко Станислав, 3.1
mi-sts/spbu_2020_c_homeworks pull request #12
Opened 2020-10-09 13:25 UTC by mi-sts

2020-10-09 18:46 UTC, SokolovYaroslav requested changes
Почти всё ок

2020-10-09 18:46 UTC, SokolovYaroslav commented on CMakeLists.txt
> +        )
Странные отступы

2020-10-09 18:46 UTC, SokolovYaroslav commented on CMakeLists.txt
>  target_link_libraries(task_2.3 library)
Файл без последнего отступа -- зло

2020-10-09 18:46 UTC, SokolovYaroslav commented on homework_3/task_1.c
> +    printf("Демонстрация работоспособности АТД \"List\":\n");
Рофл. Лайк от Терехова

2020-10-09 18:46 UTC, SokolovYaroslav commented on library/list/list.h
> +#include <stdbool.h>
Обычно инклуды после стражей ставят

2020-10-09 18:46 UTC, SokolovYaroslav commented on library/list/list.h
> +int listSize(List* list);
Обычно название функции -- это глагол

2020-10-09 18:46 UTC, SokolovYaroslav commented on library/list/list.c
> +ListElement* retrieve(int position, List* list)
А если позиция отрицательна? А если она слишком большая?

2020-10-09 18:46 UTC, SokolovYaroslav commented on library/list/list.c
> +bool deleteElement(int postion, List* list)
Очепятка

2020-10-09 18:46 UTC, SokolovYaroslav commented on library/list/list.c
> +        return;
Я бы ожидал хотя бы пустой строки. А так кажется, что эта функция просто не работет

2020-10-11 13:00 UTC, mi-sts commented on homework_3/task_1.c
> +    printf("Демонстрация работоспособности АТД \"List\":\n");
:)

2020-10-11 13:55 UTC, SokolovYaroslav requested changes

2020-10-11 13:55 UTC, SokolovYaroslav commented on homework_3/task_1.c
> +}
Чего сразу везде не добавил пустую строчку?

2020-10-17 18:39 UTC, SokolovYaroslav requested changes

2020-10-17 18:39 UTC, SokolovYaroslav commented on library/list/list.c
> +
Валгринд шепнул на ушко, что тут size не инциализируется.
Вообще, там он огромную пачку ошибок выдал, у всех ли ноги растут -- хз, надо разобраться и всё починить.

2020-10-17 18:39 UTC, SokolovYaroslav commented on library/list/list.c
> +
Чет я в прошлый раз видимо забыл чекнуть валгриндом.

2020-10-18 13:47 UTC, merged