20.Б10-мм, Мищенко Станислав, 3.2
mi-sts/spbu_2020_c_homeworks pull request #13
Opened 2020-10-12 15:30 UTC by mi-sts

2020-10-17 18:42 UTC, SokolovYaroslav requested changes
И снова валгринд ругается.

2020-10-17 18:42 UTC, SokolovYaroslav commented on library/list/list.c
> +ListElement* getNextElement(ListElement* previousElement, List* list)
По название невозможно понять, что тут по циклу берётся следующий

2020-10-18 13:49 UTC, SokolovYaroslav commented
Подтяни мастер и пингуй. Сейчас всё хорошо

2020-10-18 16:26 UTC, mi-sts commented
> Подтяни мастер и пингуй. Сейчас всё хорошо
Предыдущий пинг ещё висит.

2020-10-18 17:25 UTC, merged