20.Б10-мм, Мищенко Станислав, 4.2
mi-sts/spbu_2020_c_homeworks pull request #17
Opened 2020-10-16 18:19 UTC by mi-sts

2020-10-17 12:52 UTC, SpirinEgor requested changes
Валгринд выдаёт больше 100 ошибок...
Из них 1 утечка, проблемы с вводом и выводом.
Кажется, что много ошибок идёт из-за strlen, вроде известная бага (на винде может и не быть такого).
Но некоторые ошибки точно по силам тебе исправить :)

2020-10-17 12:52 UTC, SpirinEgor commented on homework_4/task_2.c
> +        char* exponentialForm = (char*)malloc(75 * sizeof(char));
Что за 75? Откуда взялось это число?

2020-10-17 12:52 UTC, SpirinEgor commented on homework_4/task_2.c
> +    long long exponentValue = (long long)convertBinaryNotationToDouble(exponentBinary) - (long long)getBinaryDegreeValue(10) + 1; // Получем исходное значение порядка.
Добавь перенос строки после знака `=`. Эта строчка в экран то не помещается на гитхабе, слишком длинная.

2020-10-17 22:10 UTC, mi-sts commented on homework_4/task_2.c
> +    long long exponentValue = (long long)convertBinaryNotationToDouble(exponentBinary) - (long long)getBinaryDegreeValue(10) + 1; // Получем исходное значение порядка.
CLang что-то ни в какую не хочет принимать такой формат

2020-10-21 13:28 UTC, SpirinEgor requested changes
Так как у тебя файлы прокопировались, то смотри комментарии в 4.3
Здесь у тебя ещё больше ошибок, помимо чтения вне границ выделенной памяти ещё записываешь туда же, а также используешь неинициализированные значения (valgrind всё это показывает)

2020-11-01 12:49 UTC, SpirinEgor approved these changes

2020-11-01 12:51 UTC, SpirinEgor commented
Разреши конфликты мерджа и пингани меня в телеграмме, чтобы я зачёл задачу.

2020-11-01 15:51 UTC, merged