20.Б10-мм, Мищенко Станислав, 2.2
mi-sts/spbu_2020_c_homeworks pull request #8
Opened 2020-09-30 01:28 UTC by mi-sts

2020-09-30 07:54 UTC, nbirillo requested changes

2020-09-30 07:54 UTC, nbirillo commented on homework_2/task_2.c
> +int main()
Ты в самом начале забыл убрать вывод загаданного числа
![image](https://user-images.githubusercontent.com/8993915/94655566-75be6b00-0307-11eb-97ca-9f40c06bb352.png)
Но за оформление прям спасибо, классно выглядит!

2020-09-30 07:54 UTC, nbirillo commented on homework_2/task_2.c
> +        input[i] = ' ';
Это можно заменить на `memset`. Вообще в принципе заполнение каким-то дефолтным значением динамических массивов лучше делать с помощью `memset`

2020-09-30 07:54 UTC, nbirillo commented on homework_2/task_2.c
> +    return randomNumber;
По правилам игры должно генерироваться число с неповторяющимися цифрами

2020-09-30 07:54 UTC, nbirillo commented on homework_2/task_2.c
> +    return (number >= leftNumber) && (number <= rightNumber);
Это не сработает, если я введу число `0004` например (формально оно длины 4). Если ты пользователю запрещаешь вводить первую цифру `0`, напиши об этом ему и гарантируй, что первая цифра будет не ноль (так как тебе все равно надо переписать генерацию)

2020-09-30 07:54 UTC, nbirillo commented on homework_2/task_2.c
> +    }
Это ведь просто заполнение дефолтным значением? Если так, то используй `memset`. В цикле лучше использовать `i`, `j`, `k` для счетчиков

2020-09-30 07:54 UTC, nbirillo commented on homework_2/task_2.c
> +    *cows = findCows(sharedPlayerNumber, sharedSecretNumber, numberLength, isPlayerPositionChecked, isSecretPositionChecked);
Как-то у тебя слишком много проходов - в bulls один, а потом еще в cows два. Так точно не пойдет

2020-09-30 07:54 UTC, nbirillo commented on homework_2/task_2.c
> +    while (!((input[0] == 's' || input[0] == 'e') && strlen(input) == 1)) {
` input[0] == 'e' ` на это у тебя есть функция вообще, сделай тогда уж еще одну на проверку, что вызывается старт игры и тут вызывай их. Кажется еще, что сначала лучше проверить `strlen(input) == 1`, так как если это будет неверно и у тебя стоит `&&`, то он не будет проверять условия дальше. А если это верно, у тебя всегда будет 0 элемент в массиве например и не будет ошибки

2020-10-01 19:43 UTC, SpirinEgor commented
Что-то чекер стайлгайда не работает

2020-10-05 13:38 UTC, nbirillo requested changes

2020-10-05 13:38 UTC, nbirillo commented on homework_2/task_2.c
> +    int rightBorder = (int)pow(10, numberLength); // Минимальное число большей длины.
Зачем они нужны?

2020-10-05 13:38 UTC, nbirillo commented on homework_2/task_2.c
> +    currentDigit = (rand() % 9) + 1; // Добавление старшего ненулевого разряда.
А почему сразу не написать `int currentDigit = (rand() % 9) + 1` ?
и `digitIndex = 1`?

2020-10-05 13:38 UTC, nbirillo commented on homework_2/task_2.c
> +                }
Вынеси в отдельную функцию

2020-10-05 13:38 UTC, nbirillo commented on homework_2/task_2.c
> +
Ну кажетя достаточно одной функции, которая принимает на вход `char* input` и проверяет, а дальше уже вызывать с нужными параметрами

2020-10-05 13:38 UTC, nbirillo commented on homework_2/task_2.c
> +int scanPlayerNumber(int* playerNumber, int numberLength)
А чего она `int`, а ничего не возвращает?

2020-10-05 13:38 UTC, nbirillo commented on homework_2/task_2.c
> +        sharedNumber[i] = numberDigit;
Может можно делить на 10? будет попроще

2020-10-05 13:38 UTC, nbirillo commented on homework_2/task_2.c
> +void winCheck(int bulls, int numberLength, bool* isNewGame, char* input, int inputLength)
Лучше `winCheck` -> `isWin`

2020-10-09 11:43 UTC, nbirillo requested changes

2020-10-09 11:43 UTC, nbirillo commented on homework_2/task_2.c
> +    return 3;
Обычно в дефолтных случаях возвращают -1 :)

2020-10-09 11:43 UTC, nbirillo commented on homework_2/task_2.c
> +    return 3;
Но вообще я имела в виду что-то такое: 
```
bool isEqual(char* input, char symbol) {
   return (input[0] == symbol)
}
```
(названия могут быть другие) и чтобы ты ее вызывал с разным `char` параметром

2020-10-09 11:43 UTC, nbirillo commented on homework_2/task_2.c
> +    int leftNumber = (int)pow(10, numberLength - 1); // Минимальное число заданной длины.
Раз это граница диапазона, может быть `leftBorder` и `rightBorder`?

2020-10-12 07:00 UTC, nbirillo requested changes
Небольшие правки, в остальном нормально. Еще конфликты, конечно же

2020-10-12 07:00 UTC, nbirillo commented on homework_2/task_2.c
> +}
Как-то пропустила видимо до этого, так писать плохо. Сделай аналогично функции `isInputEqual` - то есть, если ты возвращаешь `bool` значение, полученное в `if`, то можно его и вернуть, а не писать еще `true` и `false`

2020-10-12 07:00 UTC, nbirillo commented on homework_2/task_2.c
> +    while (!isNumberInRange(numberLength, *playerNumber)) {
Проверь везде типы. Например тут функция `isNumberInRange` принимает `int`, а `playerNumber` это `long`

2020-10-12 15:01 UTC, nbirillo approved these changes
Разреши конфликты и зачту

2020-10-12 15:38 UTC, merged