20.Б10-мм, Мищенко Станислав, 2.3
mi-sts/spbu_2020_c_homeworks pull request #9
Opened 2020-09-30 20:48 UTC by mi-sts

2020-10-01 19:46 UTC, SpirinEgor requested changes

2020-10-01 19:46 UTC, SpirinEgor commented on CMakeLists.txt
> -add_executable(task_2.1 homework_2/task_1.c)
Зачем удаляешь?

2020-10-01 19:46 UTC, SpirinEgor commented on homework_2/task_3.c
> +int main()
Раздели на функции

2020-10-01 19:46 UTC, SpirinEgor commented on homework_2/task_3.c
> +        array[i] = temp;
Давно уже надо было сделать функцию swap в библиотеке и использовать её

2020-10-05 13:24 UTC, nbirillo requested changes

2020-10-05 13:24 UTC, nbirillo commented on homework_2/task_3.c
> +    for (int i = 0; i < arrayLength; i++)
А чего тут используешь `i++`, а не `++i`?

2020-10-09 11:45 UTC, nbirillo approved these changes
Зачтено!

2020-10-09 11:45 UTC, merged